name: Validate appstream metadata xml
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths:
      - packaging/app.comaps.comaps.metainfo.xml
      - .forgejo/workflows/appstream-check.yaml # Run check on self change

jobs:
  validate-appstream:
    name: Validate appstream metadata xml
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub/flatpak-builder-lint:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            packaging/app.comaps.comaps.metainfo.xml
  
      - name: Lint appstream data with Flatpak Builder
        run: flatpak-builder-lint appstream packaging/app.comaps.comaps.metainfo.xml

      - name: Run appstreamcli in pedantic mode
        run: appstreamcli validate --pedantic packaging/app.comaps.comaps.metainfo.xml