name: Coverage Report
on:
  workflow_dispatch: # Manual trigger

# Cancels previous jobs if the same branch or PR was updated again.
concurrency:
  group: ${{ github.workflow }}-coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SUBMODULE_CACHE_PATHS: |
    .git/modules
    3party/CMake-MetalShaderSupport
    3party/Vulkan-Headers
    3party/boost
    3party/expat
    3party/fast_double_parser
    3party/fast_obj
    3party/freetype/freetype
    3party/gflags
    3party/glaze
    3party/glfw
    3party/glm
    3party/googletest
    3party/harfbuzz/harfbuzz
    3party/icu/icu
    3party/imgui/imgui
    3party/jansson/jansson
    3party/just_gtfs
    3party/protobuf/protobuf
    3party/pugixml/pugixml
    3party/utfcpp
    tools/kothic
    tools/osmctools

jobs:
  coverage:
    name: Generate coverage report
    runs-on: comaps-android
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 100 # enough to get all commits for the current day

      - name: Cache world map
        uses: actions/cache@v4
        with:
          path: data/world_mwm
          key: world-mwm

      - name: Calculate submodules cache key
        id: submodules_cache_key
        shell: bash
        run: echo value=`git submodule status | sha256sum | head -c64` >> $FORGEJO_OUTPUT

      - uses: actions/cache/restore@v4
        with:
          path: ${{ env.SUBMODULE_CACHE_PATHS }}
          key: submodules-${{ steps.submodules_cache_key.outputs.value }}
          restore-keys: |
            submodules-

      - name: Sync and update submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --depth 1 --init --recursive

      - uses: actions/cache/save@v4
        with:
          path: ${{ env.SUBMODULE_CACHE_PATHS }}
          key: submodules-${{ steps.submodules_cache_key.outputs.value }}

      - name: Configure ccache
        uses: https://github.com/hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.workflow }}-coverage

      - name: Compile
        shell: bash
        env:
          CC: clang
          CXX: clang++
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
          SKIP_MAP_DOWNLOAD: 1
          # -g1 should slightly reduce build time.
          CMAKE_C_FLAGS: -g1
          CMAKE_CXX_FLAGS: -g1
        run: ./tools/unix/build_omim.sh -d coverage

      - name: Tests
        shell: bash
        working-directory: build
        env:
          QT_QPA_PLATFORM: "offscreen"
          # generator_integration_tests - https://github.com/organicmaps/organicmaps/issues/225
          # opening_hours_integration_tests - https://github.com/organicmaps/organicmaps/issues/219
          # opening_hours_supported_features_tests - https://github.com/organicmaps/organicmaps/issues/219
          # routing_integration_tests - https://github.com/organicmaps/organicmaps/issues/221
          # shaders_tests - https://github.com/organicmaps/organicmaps/issues/223
          # world_feed_integration_tests - https://github.com/organicmaps/organicmaps/issues/215
          CTEST_EXCLUDE_REGEX: "generator_integration_tests|opening_hours_integration_tests|opening_hours_supported_features_tests|routing_benchmarks|routing_integration_tests|routing_quality_tests|search_quality_tests|storage_integration_tests|shaders_tests|world_feed_integration_tests"
        run: |
          locale-gen en_US
          locale-gen en_US.UTF-8
          locale-gen es_ES
          locale-gen es_ES.UTF-8
          locale-gen fr_FR
          locale-gen fr_FR.UTF-8
          locale-gen ru_RU
          locale-gen ru_RU.UTF-8
          update-locale
          ./tools/unix/run_tests.sh -b ../omim-build-debug -e "$CTEST_EXCLUDE_REGEX" -s full

      - name: Run coverage report generation
        shell: bash
        working-directory: build
        run: |
          cmake --build . --target omim_coverage
          cat coverage_report/summary.txt

      - name: Archive the coverage report
        working-directory: build/coverage_report
        run: zip -r coverage_report.zip html/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage_report/coverage_report.zip
